version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jdbc:postgresql://localhost:5432/streamlined-service-portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
